### ISSUE TITLE
how to clear RxListAdapter 

### ISSUE THREAD

**Issue by ynntk4815** [ogaclejapan/RxBinding#1]
https://github.com/ogaclejapan/RxBinding/wiki/RxListAdapter#synchronization-of-list

I run the code  and found listAdapter.getCount() not 0 after call master.clear()
I sure the list is clear . seem not easy to clear listAdapter

**Comment by ogaclejapan** [comment]
Thank you for reporting.

I have notified the clear events in the Scheduler (Handler).
Immediately call and it is not a 0 result might be returned.

The sample code I will fix later

**Comment by ogaclejapan** [comment]
Sorry, it was implemented mistake.
I added the control of a clear event.
