### ISSUE TITLE
is this an error in the wiki?

### ISSUE THREAD

**Issue by sirvon** [ogaclejapan/RxBinding#3]
``` shell
RxEvent

onNameChanged.bind(onOtherNameChanged);

onOtherNameChanged.post("rxbinding");
//If subscribe to the Observable<T> will be notified of the post value.
//onNameChanged.asObservable().subscribe(action) -> "ogaclejapan"

```

if onNameChanged binded to onOtherNameChanged and string "rxbinding" was posted to onOtherNameChanged,
shouldn't onNameChanged be "rxbinding" not "ogaclejapan" ??

**Comment by ogaclejapan** [comment]
Hi, @sirvon 
Thank you for reporting :+1: 

Oh.. sorry, wiki is incorrect.
Right now it was fixed :)
